version = 1

test_patterns = [
    "tests/**",
    "test_*.py",
    "*/test/**",
    "test*.py",
    "integration_tests/test_*.py",
]

exclude_patterns = [
    "migrations/**",
    "**/migrations/**",
    "/dist/*min.js",
    "bin/**",
    "**/node_modules/",
    "node_modules/**",
    "js/**/*.min.js",
    "public/**,",
    "dist/**",
    "**/static/**",
]

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
plugins = ["vue"]
environment = ["nodejs", "browser", "jest", "jquery"]
module_system = "es-modules"
style_guide = "airbnb"
dialect = "typescript"
dependency_file_paths = [
    "src/client/package.json",
    "src/server/package.json",
    "src/package.json",
    "frontend/package.json",
    "app/package.json",
    "package.json",
]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "python"
enabled = true

[analyzers.meta]
runtime_version = "3.x.x"
type_checker = "mypy"
max_line_length = 120
skip_doc_coverage = ["module", "magic", "init"]
additional_builtins = ["_", "pretty_output"]

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "black"
enabled = true
