---
restylers:
  - yapf:
      enabled: false
  - autopep8:
      enabled: false
  - prettier:
      enabled: false
  - reorder-python-imports:
      enabled: false
  - clang-format:
      enabled: false
  - jq:
      enabled: false
  - "*"
